server:
  port: 8080

javax:
  sql:
    DataSource:
      greetingDataSource:
#        dataSourceClassName: org.h2.jdbcx.JdbcDataSource
#        dataSource:
#          url: jdbc:h2:mem:greeting;INIT=RUNSCRIPT FROM 'classpath:greeting.ddl'
#          user: sa
#          password: ""
        dataSourceClassName: com.mysql.cj.jdbc.MysqlDataSource
        dataSource:
          url: jdbc:mysql://rpi4:3306/helidon
          user: mysql
          password: Welcome1
